Repository wecode-bootcamp-korea/50-3rd-Fin_Pong-frontend, pull requests merged in 2023-11, with the labels that each got.

#3 [50기 황수현]Add:setting UI구성완료
  package-lock.json
  package.json
  public/data/category.json
  public/data/sample.json
  public/data/type.json
  public/data/userList.json
  public/images/caret-down-solid.svg
  public/images/kakaoLogin.png
  public/images/onebooklogo.png
  public/images/onebooklogo_preview_rev_1.png
  src/pages/Setting/Setting.js
  src/pages/Setting/Setting.scss
  src/pages/Setting/component/AllowanceModal.js
  src/pages/Setting/component/AllowanceModal.scss
  src/pages/Setting/component/BudgetModal.js
  src/pages/Setting/component/BudgetModal.scss
  src/pages/Setting/component/SelectDropdown.js
  src/pages/Setting/component/SelectDropdown.scss
  src/pages/Setting/component/calenderInput.js
  src/pages/Setting/component/calenderInput.scss
  src/pages/Setting/component/completeBtn.js
  src/pages/Setting/component/completeBtn.scss
  src/utils/convert.js
Labels: 멘토 리뷰 요청

#10 [50기 황수현]Modify: API연결 완료 및 alert 내용 일부 수정
  src/pages/Setting/Setting.js
  src/pages/Setting/component/AllowanceModal.js
  src/pages/Setting/component/BudgetModal.js
Labels: 멘토 리뷰 요청

#2 [50기 김성호] DashBoard- Add. 수입/지출, 참여&생성하기 버튼 및 기능(모달창)구현
  package-lock.json
  package.json
  public/images/close.svg
  src/Router.js
  src/components/MenuBar/MenuBar.js
  src/components/MenuBar/MenuBar.scss
  src/components/MenuBar/adminImage.png
  src/components/MenuBar/onebooklogo_preview_rev_1.jpg
  src/components/MenuBar/onebooklogo_preview_rev_1.png
  src/components/MenuWrapper/MenuWrapper.js
  src/components/MenuWrapper/MenuWrapper.scss
  src/pages/Main/GraphBarChart.js
  src/pages/Main/GraphCircularChart.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Table/Table.js
Labels: 멘토 리뷰 요청

#11 Modify: css일부 수정
  src/pages/Setting/Setting.scss
  src/pages/Setting/component/AllowanceModal.js
  src/pages/Setting/component/AllowanceModal.scss
  src/pages/Setting/component/BudgetModal.js
  src/pages/Setting/component/BudgetModal.scss
  src/pages/Setting/component/CalenderInput.scss
  src/pages/Setting/component/CompleteBtn.scss
  src/pages/Setting/component/SelectDropdown.scss
Labels: 멘토 리뷰 요청

#13 Fix: GraphCircularChart 로직 수정(원형차트 월별 Text 표시, 원형차트 데이터별 Text 표시)
  src/components/MenuWrapper/MenuWrapper.scss
  src/pages/Main/GraphCircularChart.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청

#12 [50기 황수현]Modify: 로그인,메뉴바 UI 수정
  package-lock.json
  package.json
  public/images/OneBook_Logo.png
  public/images/OneBook_Logo_small.png
  public/images/onebooklogo.png
  src/Router.js
  src/components/MenuBar/MenuBar.js
  src/components/MenuBar/MenuBar.scss
  src/components/MenuWrapper/MenuWrapper.js
  src/components/MenuWrapper/MenuWrapper.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Setting/Setting.js
  src/pages/Setting/Setting.scss
  src/pages/Setting/component/AllowanceModal.js
  src/pages/Setting/component/AllowanceModal.scss
  src/pages/Setting/component/BudgetModal.js
  src/pages/Setting/component/BudgetModal.scss
  src/pages/Setting/component/CompleteBtn.scss
  src/pages/UserSignUp/UserSignUp.js
Labels: Conflict 해결 요청, 멘토 리뷰 요청, 추가 기능 구현 중

#14 Fix: GraphBarChart 컴포넌트내 불필요한 PureComponent 삭제
  src/pages/Main/GraphBarChart.js
Labels: 멘토 리뷰 요청

#17 [50기 황수현]Modify : config API 수정 및 TOKEN 수정
  public/images/OneBook_Landing_ver3.png
  src/Router.js
  src/components/MenuBar/MenuBar.js
  src/components/MenuWrapper/MenuWrapper.js
  src/config.js
  src/pages/Auth/Auth.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Main/Main.js
  src/pages/Setting/Setting.js
  src/pages/Table/Table.js
  src/pages/UserSignUp/UserSignUp.js
Labels: 완료
